In [1]:
import pandas as pd
import numpy as np

In [2]:
DATA_ID = "04"
FIGURES_FOLDER = 'figures'

In [3]:
RESULTS_FILE = f"sim_results-{DATA_ID}.csv"
CLEANED_FILE = f"sim_results_cleaned-{DATA_ID}.csv"
df = pd.read_csv(RESULTS_FILE)
df.head(5)

,case_id,Qfeed,Tfeed,cH2S,cNH3,Qreb,Pcolumn,Ecolumn,Tbottom,Ttop
0,1,47771.588241,123.890672,3347.171555,1620.335163,5.683296,6.265913,70.574537,167.940678,165.082651
1,2,50623.617128,122.623299,3069.789032,1486.845816,4.715020,6.111705,68.829504,167.080252,162.932376
2,3,50746.292665,121.807057,3371.565556,1127.478207,2.184803,5.918689,68.129379,157.940159,60.310114
3,4,50684.170480,122.771663,897.095348,1631.585240,3.655940,6.046517,68.594902,166.556040,157.553113
4,6,48783.610674,121.696238,3261.478793,2693.326265,2.897892,6.011957,71.157917,165.956645,65.802812

In [4]:
print('Data rows:', df.shape[0])

Data rows: 976

In [5]:
# Observing data tail
df.tail(5)

,case_id,Qfeed,Tfeed,cH2S,cNH3,Qreb,Pcolumn,Ecolumn,Tbottom,Ttop
971,960,49933.396958,119.171765,2964.230224,1780.009414,2.418067,6.289987,66.942409,159.952015,60.208242
972,991,50979.978198,122.748431,1756.794267,2554.107304,2.351476,6.119361,67.232895,161.383088,60.108322
973,643,49708.721102,121.226258,892.585506,1422.673110,2.953354,5.802137,67.958048,165.096787,66.832016
974,798,48369.319533,119.907352,2256.873169,2551.894152,3.588562,6.009392,70.186271,166.237408,147.126081
975,800,51116.494140,124.402909,2893.796257,2378.532218,2.114825,6.106942,67.695956,158.970537,60.222943

In [6]:
# Observing a sample
SAMPLE_SIZE = 10
start = np.random.randint(0, len(df) - SAMPLE_SIZE + 1)
sample_df = df.iloc[start : start + SAMPLE_SIZE]

sample_df.head(SAMPLE_SIZE)

,case_id,Qfeed,Tfeed,cH2S,cNH3,Qreb,Pcolumn,Ecolumn,Tbottom,Ttop
23,28,49172.997211,119.368208,2988.333428,1508.722351,4.608562,5.856319,73.113512,165.684701,161.378452
24,29,50079.671806,124.189413,3357.890402,958.643965,3.036891,6.202662,69.521047,167.404159,67.744434
25,31,49382.691245,120.680357,2522.540723,1567.453860,4.945059,5.762210,73.134985,165.176447,161.774106
26,32,51306.462370,123.815120,1715.219725,2022.578998,2.167889,5.842964,71.267100,159.213837,60.084545
27,33,51537.668191,119.121089,945.448202,2054.521066,2.962634,6.091556,67.424704,166.471662,60.576117
28,34,48400.137451,121.124588,2629.296046,852.087857,2.988558,6.223735,68.428068,167.525831,63.378001
29,35,51465.958353,123.386077,3075.360412,2572.542300,3.271887,5.959736,68.745927,165.816908,103.555283
30,36,48452.095591,121.051872,2911.831660,1388.371838,5.646437,5.860496,72.948710,165.738378,162.983346
31,37,47752.554881,121.025063,1758.206271,960.696338,3.200776,5.948888,72.415775,166.063573,91.445511
32,38,49856.632931,122.262584,1139.574162,2871.226322,4.218174,5.915311,69.390722,165.896321,160.670730

In [7]:
df.describe()

,case_id,Qfeed,Tfeed,cH2S,cNH3,Qreb,Pcolumn,Ecolumn,Tbottom,Ttop
count,976.000000,976.000000,976.000000,976.000000,976.000000,976.000000,976.000000,976.000000,976.000000,976.000000
mean,504.562500,49995.259536,122.019970,2210.139150,1872.570075,4.044402,5.999096,70.018045,165.653584,130.005101
std,289.134589,1448.225465,1.763657,750.477802,651.942962,1.133307,0.172716,2.017436,2.228586,43.687916
min,1.000000,47504.803943,118.955300,876.170054,750.837120,2.013050,5.700417,66.504578,154.501411,60.014619
25%,253.750000,48739.771498,120.497556,1569.668431,1308.580453,3.073959,5.850176,68.287997,165.135559,72.022210
50%,506.500000,49983.516513,122.031123,2213.811917,1873.472862,4.047316,5.999352,70.034742,166.086793,159.727016
75%,755.250000,51247.948017,123.554594,2857.895279,2438.948102,5.023322,6.147492,71.763167,167.062152,162.801932
max,1000.000000,52496.503474,125.044175,3499.583766,2997.968327,5.998898,6.299700,73.491205,168.106406,165.655281

In [8]:
# Check for NaN values
nan_check = df.isna().sum()
print("NaN values per column:\n", nan_check)

NaN values per column:
 case_id    0
Qfeed      0
Tfeed      0
cH2S       0
cNH3       0
Qreb       0
Pcolumn    0
Ecolumn    0
Tbottom    0
Ttop       0
dtype: int64

In [9]:
# Check for zero values
zero_check = (df == 0).sum()
print("\nZero values per column:\n", zero_check)

Zero values per column:
 case_id    0
Qfeed      0
Tfeed      0
cH2S       0
cNH3       0
Qreb       0
Pcolumn    0
Ecolumn    0
Tbottom    0
Ttop       0
dtype: int64

In [10]:
# Filter rows with NaN values
nan_rows = df[df.isna().any(axis=1)]
print("Rows with NaN values:\n", nan_rows)

Rows with NaN values:
 Empty DataFrame
Columns: [case_id, Qfeed, Tfeed, cH2S, cNH3, Qreb, Pcolumn, Ecolumn, Tbottom, Ttop]
Index: []

In [11]:
# Drop rows with any NaN values
df = df.dropna()

# Optionally, reset the index if needed
df = df.reset_index(drop=True)

# Check for NaN values
nan_check = df.isna().sum()
print("NaN values per column:\n", nan_check)

NaN values per column:
 case_id    0
Qfeed      0
Tfeed      0
cH2S       0
cNH3       0
Qreb       0
Pcolumn    0
Ecolumn    0
Tbottom    0
Ttop       0
dtype: int64

In [12]:
df.shape

(976, 10)

In [13]:
# Export processed csv
df.to_csv(CLEANED_FILE, index=False)

In [14]:
# Print differences between original and cleaned data
df1 = pd.read_csv(RESULTS_FILE)
df2 = pd.read_csv(CLEANED_FILE)

diff_rows = df1[df1.ne(df2).any(axis=1)]
print(diff_rows)

Empty DataFrame
Columns: [case_id, Qfeed, Tfeed, cH2S, cNH3, Qreb, Pcolumn, Ecolumn, Tbottom, Ttop]
Index: []